# Rename this file to secrets.toml and add your actual API keys

[api_keys]
alpha_vantage = "your_alpha_vantage_api_key_here"
quandl = "your_quandl_api_key_here"

[database]
host = "your_database_host"
port = 5432
database = "your_database_name"
username = "your_username"
password = "your_password"
